steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ppl-teknokrat', '.']
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ppl-teknokrat']
    # deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'ppl-teknokrat',
        '--image',
        'gcr.io/$PROJECT_ID/ppl-teknokrat:latest',
        '--region',
        'asia-southeast1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--cpu',
        '4',
        '--memory',
        '4Gi',
        '--env-vars-file',
        '.env.yaml',
        '--port',
        '8000',
      ]