# Generated by Django 4.1.7 on 2023-04-11 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamar',
            name='berkas',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lamar',
            name='lowongan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.lowongan'),
        ),
        migrations.AlterField(
            model_name='lamar',
            name='subject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lamar',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
