# Generated by Django 4.1.7 on 2023-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerKuesioners',
        ),
        migrations.DeleteModel(
            name='Excel',
        ),
        migrations.DeleteModel(
            name='FailedJobs',
        ),
        migrations.DeleteModel(
            name='FormKepuasan',
        ),
        migrations.DeleteModel(
            name='JawabanFormKepuasan',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Migrations',
        ),
        migrations.DeleteModel(
            name='MinimumSalaryByRegion',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.RemoveField(
            model_name='questanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subkuesioner',
            name='kuesioner',
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Kuesioner',
        ),
        migrations.DeleteModel(
            name='QuestAnswer',
        ),
        migrations.DeleteModel(
            name='SubKuesioner',
        ),
    ]
