# Generated by Django 4.1.7 on 2023-04-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_alter_lamar_berkas_alter_lamar_lowongan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamar',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ditolak', 'Ditolak'), ('Diterima', 'Diterima')], default='Pending', max_length=255),
        ),
    ]
