# Generated by Django 4.1.7 on 2023-03-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_delete_answerkuesioners_delete_excel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowongan',
            name='buka_lowongan',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='status',
            field=models.CharField(choices=[('0', 'Belum terverifikasi'), ('1', 'Sudah terverifikasi'), ('2', 'Lowongan buka'), ('3', 'Lowongan ditutup')], default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
