# Generated by Django 4.1.7 on 2023-03-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_lowongan_buka_lowongan_alter_lowongan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowongan',
            name='requirements',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='deskripsi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='status',
            field=models.CharField(choices=[('Belum terverifikasi', 'Belum terverifikasi'), ('Sudah terverifikasi', 'Sudah terverifikasi'), ('Ditolak', 'Sudah Ditolak'), ('Buka', 'Buka'), ('Tutup', 'Tutup')], default='Belum terverifikasi', max_length=255),
        ),
    ]
