# Generated by Django 4.1.7 on 2023-04-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0004_alter_lamar_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="asal_sekolah",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cv", name="instansi", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cv",
            name="jenis_kontak",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cv",
            name="keterangan_pendidikan",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cv",
            name="keterangan_posisi",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cv", name="kontak", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cv",
            name="lama_instansi",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="cv", name="masa_waktu", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="users",
            name="tempat_lahir",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
