# Generated by Django 4.1.7 on 2023-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_lowongan_requirements_alter_lowongan_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowongan',
            name='gaji',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='lama_pengalaman',
            field=models.PositiveIntegerField(),
        ),
    ]
