# Generated by Django 4.1.7 on 2023-03-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0003_alter_cv_users_id"),
        ("jobseeker", "0004_lowongan_requirements_alter_lowongan_deskripsi_and_more"),
    ]

    operations = []
