# Generated by Django 4.1.7 on 2023-03-09 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_alter_lowongan_gaji_alter_lowongan_lama_pengalaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowongan',
            name='users_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
