# Generated by Django 4.1.7 on 2023-04-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0005_alter_cv_asal_sekolah_alter_cv_instansi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="tempat_lahir",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
