# Generated by Django 4.1.7 on 2023-03-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_merge_20230310_1253'),
        ('jobseeker', '0006_alter_lowongan_users_id'),
    ]

    operations = [
    ]
