# Generated by Django 4.1.7 on 2023-03-13 10:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_merge_20230313_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowongan',
            name='deskripsi',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='lowongan',
            name='requirements',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
