# Generated by Django 4.1.7 on 2023-04-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0007_alter_users_tgl_lahir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="tgl_lahir",
            field=models.DateField(blank=True, null=True),
        ),
    ]
