# Generated by Django 4.1.7 on 2023-05-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_alter_users_tgl_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
