# Generated by Django 4.1.7 on 2023-03-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_alter_lowongan_deskripsi_alter_lowongan_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowongan',
            name='batas_pengumpulan',
            field=models.DateField(null=True),
        ),
    ]
